[build]
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.148.1"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"